namespace ArnoldVinkCode
{
    public partial class AVInputOutputClass
    {
        public enum KeysModifierVirtual : byte
        {
            None = 0x0000,
            Ctrl = 0x0001,
            Alt = 0x0002,
            Shift = 0x0004,
            Windows = 0x0008
        }

        public enum KeysVirtual : byte
        {
            None = 0x00,
            LeftButton = 0x01,
            RightButton = 0x02,
            Cancel = 0x03,
            MiddleButton = 0x04,
            XButton1 = 0x05,
            XButton2 = 0x06,
            BackSpace = 0x08,
            Tab = 0x09,
            LineFeed = 0xA,
            Clear = 0x0C,
            Enter = 0x0D,
            Shift = 0x10,
            ShiftLeft = 0xA0,
            ShiftRight = 0xA1,
            Control = 0x11,
            ControlLeft = 0xA2,
            ControlRight = 0xA3,
            Alt = 0x12,
            AltLeft = 0xA4,
            AltRight = 0xA5,
            Pause = 0x13,
            CapsLock = 0x14,
            KanaMode = 0x15,
            HangulMode = 0x15,
            JunjaMode = 0x17,
            FinalMode = 0x18,
            HanjaMode = 0x19,
            KanjiMode = 0x19,
            Escape = 0x1B,
            IMEConvert = 0x1C,
            IMENonConvert = 0x1D,
            IMEAccept = 0x1E,
            IMEModeChange = 0x1F,
            Space = 0x20,
            PageUp = 0x21,
            PageDown = 0x22,
            End = 0x23,
            Home = 0x24,
            ArrowLeft = 0x25,
            ArrowUp = 0x26,
            ArrowRight = 0x27,
            ArrowDown = 0x28,
            Select = 0x29,
            Print = 0x2A,
            Execute = 0x2B,
            PrintScreen = 0x2C,
            Insert = 0x2D,
            Delete = 0x2E,
            Help = 0x2F,
            Digit0 = 0x30,
            Digit1 = 0x31,
            Digit2 = 0x32,
            Digit3 = 0x33,
            Digit4 = 0x34,
            Digit5 = 0x35,
            Digit6 = 0x36,
            Digit7 = 0x37,
            Digit8 = 0x38,
            Digit9 = 0x39,
            A = 0x41,
            B = 0x42,
            C = 0x43,
            D = 0x44,
            E = 0x45,
            F = 0x46,
            G = 0x47,
            H = 0x48,
            I = 0x49,
            J = 0x4A,
            K = 0x4B,
            L = 0x4C,
            M = 0x4D,
            N = 0x4E,
            O = 0x4F,
            P = 0x50,
            Q = 0x51,
            R = 0x52,
            S = 0x53,
            T = 0x54,
            U = 0x55,
            V = 0x56,
            W = 0x57,
            X = 0x58,
            Y = 0x59,
            Z = 0x5A,
            WindowsLeft = 0x5B,
            WindowsRight = 0x5C,
            ContextMenu = 0x5D,
            Sleep = 0x5F,
            Numpad0 = 0x60,
            Numpad1 = 0x61,
            Numpad2 = 0x62,
            Numpad3 = 0x63,
            Numpad4 = 0x64,
            Numpad5 = 0x65,
            Numpad6 = 0x66,
            Numpad7 = 0x67,
            Numpad8 = 0x68,
            Numpad9 = 0x69,
            NumpadMultiply = 0x6A,
            NumpadAdd = 0x6B,
            NumpadSeparator = 0x6C,
            NumpadSubtract = 0x6D,
            NumpadDecimal = 0x6E,
            NumpadDivide = 0x6F,
            F1 = 0x70,
            F2 = 0x71,
            F3 = 0x72,
            F4 = 0x73,
            F5 = 0x74,
            F6 = 0x75,
            F7 = 0x76,
            F8 = 0x77,
            F9 = 0x78,
            F10 = 0x79,
            F11 = 0x7A,
            F12 = 0x7B,
            F13 = 0x7C,
            F14 = 0x7D,
            F15 = 0x7E,
            F16 = 0x7F,
            F17 = 0x80,
            F18 = 0x81,
            F19 = 0x82,
            F20 = 0x83,
            F21 = 0x84,
            F22 = 0x85,
            F23 = 0x86,
            F24 = 0x87,
            NumpadLock = 0x90,
            ScrollLock = 0x91,
            BrowserBack = 0xA6,
            BrowserForward = 0xA7,
            BrowserRefresh = 0xA8,
            BrowserStop = 0xA9,
            BrowserSearch = 0xAA,
            BrowserFavorites = 0xAB,
            BrowserHome = 0xAC,
            VolumeMute = 0xAD,
            VolumeDown = 0xAE,
            VolumeUp = 0xAF,
            MediaNextTrack = 0xB0,
            MediaPreviousTrack = 0xB1,
            MediaStop = 0xB2,
            MediaPlayPause = 0xB3,
            LaunchMail = 0xB4,
            SelectMedia = 0xB5,
            LaunchApplication1 = 0xB6,
            LaunchApplication2 = 0xB7,
            OEMSemicolon = 0xBA,
            OEMPlus = 0xBB,
            OEMComma = 0xBC,
            OEMMinus = 0xBD,
            OEMPeriod = 0xBE,
            OEMQuestion = 0xBF,
            OEMTilde = 0xC0,
            OEMOpenBracket = 0xDB,
            OEMPipe = 0xDC,
            OEMCloseBracket = 0xDD,
            OEMQuote = 0xDE,
            OEMBackSlash = 0xE2,
            Zoom = 0xFB
        }

        //Virtual keys that prefer extended
        public static KeysVirtual[] KeysVirtualExtended =
        {
            KeysVirtual.ArrowUp,
            KeysVirtual.ArrowDown,
            KeysVirtual.ArrowLeft,
            KeysVirtual.ArrowRight,
            KeysVirtual.Delete
        };
    }
}